services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.12-alpine
    container_name: tg-dbot-clickhouse-server
    profiles: ["prod"]
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./../../configs/clickhouse/users.xml:/etc/clickhouse-server/users.d/users.xml:ro
      - ./../../configs/clickhouse/disable_logs.xml:/etc/clickhouse-server/config.d/z_disable_logs.xml:ro
      - ./../../configs/clickhouse/config.xml:/etc/clickhouse-server/config.d/config.xml:ro
    environment:
      CLICKHOUSE_DB: otel
      ADMIN_PASSWORD: ${CLICKHOUSE_PASSWORD}
      OTEL_WRITER_PASSWORD: ${CLICKHOUSE_OTEL_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "clickhouse-client --query 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    networks:
      - tg-dbot-network

volumes:
  clickhouse_data: