services:
  ollama:
    container_name: tg-dbot-ollama
    image: ollama/ollama:0.16.2
    volumes:
      - ollama-data:/root/.ollama
    command: ["serve"]
    restart: unless-stopped
    ports:
      - "11434:11434"
    cpus: "2.0"
    mem_limit: 4096m
    memswap_limit: 4096m
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4096m
    networks:
      - tg-dbot-network

  llm-init:
    image: alpine/curl:8.17.0
    container_name: tg-dbot-llm-init
    depends_on:
      ollama:
        condition: service_started
    restart: "no"
    networks:
      - tg-dbot-network
    command: >
      sh -c '
        curl -sS -X POST http://ollama:11434/api/pull \
          -H "Content-Type: application/json" \
          -d "{\"name\":\"qwen3:1.7b-q8_0\",\"stream\":false}";
      '

volumes:
  ollama-data: