services:
  postgres-db:
    container_name: tg-dbot-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${PostgresConfig__PGUSER}
      POSTGRES_PASSWORD: ${PostgresConfig__PGPASS}
      POSTGRES_DB: ${PostgresConfig__PGDB}
      PGUSER: ${PostgresConfig__PGUSER}
      PGDATABASE: ${PostgresConfig__PGDB}
      UPTRACE_DB: ${PostgresConfig__UPTRACE_DB}
      UPTRACE_USER: ${PostgresConfig__UPTRACE_USER}
      UPTRACE_PASSWORD: ${PostgresConfig__UPTRACE_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PostgresConfig__PGUSER} -d ${PostgresConfig__PGDB}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./../../configs/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - tg-dbot-network

volumes:
  postgres-data: