services:
  postgres-db:
    container_name: tg-dbot-postgres
    image: postgres:18-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_PGUSER}
      POSTGRES_PASSWORD: ${POSTGRES_PGPASS}
      POSTGRES_DB: ${POSTGRES_PGDB}
      PGUSER: ${POSTGRES_PGUSER}
      PGDATABASE: ${POSTGRES_PGDB}
      UPTRACE_DB: ${POSTGRES_UPTRACE_DB}
      UPTRACE_USER: ${POSTGRES_UPTRACE_USER}
      UPTRACE_PASSWORD: ${POSTGRES_UPTRACE_PASS}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_PGUSER} -d ${POSTGRES_PGDB}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./../../configs/postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    networks:
      - tg-dbot-network

volumes:
  postgres-data: