global:
  scrape_interval: 15s

scrape_configs:
  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

remote_write:
  - url: "http://uptrace:14318/api/v1/prometheus/write"
    headers:
      uptrace-dsn: "${UPTRACE_DSN}"
